### ISSUE TITLE
Adding support for keyed blake2s hashes

### ISSUE THREAD

**Issue by crasm** [rweather/noise-java#2]
I'm working on a java implementation of wireguard and one of the needed functions is keyed blake2s hashing.

I saw the note in the `Noise.java:174` where the fallback is used:
```
// Bouncy Castle doesn't currently (June 2016) have an
// implementation of BLAKE2s, but look for the most
// obvious provider name in case one is added in the future.
```

Is support for keyed hashing something that would be relatively easy to add to the fallback implementation, or should I work on getting blake2s implemented upstream in bouncy castle? There's nothing about blake2s in the latest release or [the git master](https://github.com/bcgit/bc-java/search?utf8=%E2%9C%93&q=blake2s&type=Code).

**Comment by rweather** [comment]
It would be very easy to add keyed hashing to the fallback implementations of BLAKE2s and BLAKE2b - add a resetWithKey() function or something that takes the key as a parameter.  Bouncy Castle passes the key into a constructor but I don't know whether I like that pattern.

My separate C++ arduinolibs repository has keyed BLAKE2 hashes so the code can be easily copied from there: https://github.com/rweather/arduinolibs/tree/master/libraries/Crypto

I can take care of that this weekend unless you want to give it a try sooner and submit a patch.  There are test vectors in RFC 7693.

**Comment by crasm** [comment]
I can take a stab at it as a learning exercise, but I might not finish before the weekend.

**Comment by rweather** [comment]
Go for it, even if it takes a little longer.  I can hold off.

**Comment by crasm** [comment]
Do you mind if I add gradle to the project?

**Comment by rweather** [comment]
I don't mind at all.
