### ISSUE TITLE
Wrong nonce length?

### ISSUE THREAD

**Issue by BigPanda97** [rweather/noise-java#20]
It looks like this implementation, at least the fallback implementation, uses 64 bits / 8 bytes as nonce for AES-GCM, however, AES-GCM is specified with 96 bits / 12 bytes nonce. What's wrong here?

Also, why do I have to specify the nonce as long? That's very untypical, it should be a byte[] too.

**Comment by rweather** [comment]
The Noise protocol requires the use of 64-bit numeric nonces for consistency across all supported ciphers and simplicity of nonce management.  The AESGCM cipher pads the 64-bit value to 96 bits as part of the CipherState implementation.  Here is the relevant section of the specification:

https://noiseprotocol.org/noise.html#the-aesgcm-cipher-functions
